version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: knowledgeverse-postgres
    environment:
      POSTGRES_DB: knowledgeverse
      POSTGRES_USER: knowledgeverse_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - knowledgeverse-network

  # ChromaDB Vector Database
  chromadb:
    image: chromadb/chroma:latest
    container_name: knowledgeverse-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped
    networks:
      - knowledgeverse-network

  # KnowledgeVerse Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledgeverse-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://knowledgeverse_user:${POSTGRES_PASSWORD}@postgres:5432/knowledgeverse?sslmode=disable
      - CHROMADB_URL=http://chromadb:8000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - chromadb
    restart: unless-stopped
    networks:
      - knowledgeverse-network
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             node server.js"

volumes:
  postgres_data:
  chromadb_data:

networks:
  knowledgeverse-network:
    driver: bridge